sudo: required
service:
  - docker
before_install:
  - docker pull ubuntu:trusty
  - docker run -v $(pwd):/opt/aff3d --name build -d ubuntu:xenial sleep infinity
install:
  - docker exec build sudo apt update
  - docker exec build sudo apt install -y cmake libsdl2-dev g++
script:
  - docker exec build sh -c "cd /opt/aff3d && mkdir build && cd build && cmake .. && make"
language: c++
