sudo: required
service:
  - docker
before_install:
  - docker pull ubuntu:trusty
  - docker run -v $(pwd):/opt/aff3d --name build -d ubuntu:xenial sleep infinity
install:
  - docker exec build apt update
  - docker exec build apt install -y cmake libsdl2-dev g++
    # fix bug in the cmake SDL2 config: trailing space that is now forbidden
  - docker exec build sh -c 'sed -i "s/-lSDL2 /-lSDL/" /usr/lib/*/cmake/SDL2/sdl2-config.cmake'
script:
  - docker exec build sh -c 'cd /opt/aff3d && mkdir build && cd build && cmake .. && make'
language: c++
